"""Generate src/hershey_fonts.rs with multiple Hershey fonts in one module.
One-shot helper — run once, paste output. Picks the fonts that make sense for
map-writing: clean geometric, connected cursive, classic serif, etc.

Source: https://github.com/techninja/hersheytextjs (MIT-licensed; the underlying
Hershey glyph data is in the public domain — Dr. A.V. Hershey, NIST)."""
import json
import re
import sys
from pathlib import Path

SRC = Path(r"C:\Users\miche\AppData\Local\Temp\hershey.min.json")

# (rust_variant, json_key, display_name, blurb)
FONTS = [
    ("Simplex",  "futural",   "simplex",   "Clean single-stroke sans (Hershey simplex)"),
    ("Cursive",  "cursive",   "cursive",   "Connected handwriting — fewest visual breaks"),
    ("Script",   "scripts",   "script",    "Looser cursive, more flourishes"),
    ("Roman",    "timesr",    "roman",     "Classical serif (Times-like)"),
    ("Gothic",   "gothiceng", "gothic",    "English gothic / blackletter — dramatic but many strokes"),
]

def parse_glyphs(font):
    glyphs = {}
    total_o, n_o = 0, 0
    for i, ch in enumerate(font["chars"]):
        code = 33 + i
        if code > 126: break
        o = int(ch.get("o", 16))
        total_o += o; n_o += 1
        d = (ch.get("d") or "").strip()
        strokes = []
        if d:
            for seg in re.split(r"\s*M\s*", d):
                seg = seg.strip()
                if not seg: continue
                seg = re.sub(r"^L\s*", "", seg)
                seg = re.sub(r"\s*L\s*", " ", seg)
                pts = re.findall(r"(-?\d+),(-?\d+)", seg)
                stroke = [(int(x), int(y)) for x, y in pts]
                if len(stroke) >= 2:
                    strokes.append(stroke)
                elif len(stroke) == 1:
                    stroke.append(stroke[0])
                    strokes.append(stroke)
        # Flip y so up = +y (matches the rest of the codebase).
        strokes = [[(x, -y) for (x, y) in s] for s in strokes]
        glyphs[code] = (o, strokes)
    glyphs[32] = (round(total_o / max(n_o, 1)), [])
    return glyphs

def cap_height(glyphs):
    ys = []
    for code in range(ord("A"), ord("Z") + 1):
        g = glyphs.get(code)
        if not g: continue
        for s in g[1]:
            for (_, y) in s:
                ys.append(y)
    return (max(ys) - min(ys)) if ys else 21

j = json.loads(SRC.read_text(encoding="utf-8"))

out = sys.stdout
print = lambda *a, **k: out.write((' '.join(str(x) for x in a)) + k.get('end', '\n'))

print("// Auto-generated by extract_hershey_fonts.py — do not edit by hand..")
print("// Hershey vector fonts (public domain glyph data via hersheytextjs).")
print("// y axis: +y is UP (flipped from the source SVG-style data).")
print()
print("#[derive(Copy, Clone, Debug, PartialEq, Eq)]")
print("pub enum Font {")
for variant, _, _, _ in FONTS:
    print(f"    {variant},")
print("}")
print()
print("impl Font {")
print("    pub fn parse(s: &str) -> Option<Self> {")
print("        Some(match s.to_ascii_lowercase().as_str() {")
for variant, _, name, _ in FONTS:
    print(f'            "{name}" => Self::{variant},')
print("            _ => return None,")
print("        })")
print("    }")
print()
print("    pub fn cap_height(self) -> f64 {")
print("        match self {")
for variant, key, _, _ in FONTS:
    g = parse_glyphs(j[key])
    print(f"            Self::{variant} => {cap_height(g)}.0,")
print("        }")
print("    }")
print()
print("    pub fn glyphs(self) -> &'static [Option<&'static Glyph>; 128] {")
print("        match self {")
for variant, _, _, _ in FONTS:
    print(f"            Self::{variant} => GLYPHS_{variant.upper()},")
print("        }")
print("    }")
print("}")
print()
print("pub struct Glyph {")
print("    pub width: i16,")
print("    pub strokes: &'static [&'static [(i16, i16)]],")
print("}")
print()
for variant, key, name, blurb in FONTS:
    glyphs = parse_glyphs(j[key])
    print(f"// {variant}: {blurb}")
    print(f"#[allow(dead_code)]")
    print(f"pub static GLYPHS_{variant.upper()}: &[Option<&Glyph>; 128] = &[")
    for code in range(128):
        g = glyphs.get(code)
        if not g:
            print("    None,")
            continue
        width, strokes = g
        if not strokes:
            print(f"    Some(&Glyph {{ width: {width}, strokes: &[] }}),")
            continue
        print(f"    Some(&Glyph {{ width: {width}, strokes: &[")
        for st in strokes:
            st_lit = ", ".join(f"({x},{y})" for (x, y) in st)
            print(f"        &[{st_lit}],")
        print("    ] }),")
    print("];")
    print()
