//! Closed-loop shape geometry placed on the sphere.
//!
//! Each shape is described in unit space (characteristic radius = 1, +x = east,
//! +y = north, closed: last vertex == first), then projected onto the spherical
//! earth around a chosen center via `geodesy::destination` so leg distances are
//! correct at country scale rather than slightly off via flat-earth math.
//!
//! `place_shape` solves for the radius that yields the requested *perimeter*,
//! since "I want a 50 km loop" is the natural mental model.

use crate::geodesy::{destination, LatLon};

const CIRCLE_SEGMENTS: usize = 16;
const SMOOTH_CURVE_SEGMENTS: usize = 32;

#[derive(Copy, Clone, Debug, PartialEq, Eq)]
pub enum ShapeKind {
    Circle,
    Triangle,
    Square,
    Pentagon,
    Hexagon,
    Star,
    Heart,
    FigureEight,
    SwissCross,
    /// A simplified outline of Switzerland — drawn as a closed loop scaled to
    /// the requested perimeter. Lets you trace a mini-CH inside the country.
    Switzerland,
}

impl ShapeKind {
    /// Some shapes have a natural geographic orientation (Switzerland's
    /// outline only reads as Switzerland when north stays up). The candidate
    /// sampler skips random rotation for these so the result is always
    /// recognisable.
    pub fn has_natural_orientation(self) -> bool {
        matches!(self, Self::Switzerland)
    }

    pub fn parse(s: &str) -> Option<Self> {
        Some(match s.to_ascii_lowercase().as_str() {
            "circle" => Self::Circle,
            "triangle" => Self::Triangle,
            "square" => Self::Square,
            "pentagon" => Self::Pentagon,
            "hexagon" => Self::Hexagon,
            "star" => Self::Star,
            "heart" => Self::Heart,
            "figure-8" | "figure8" | "figureeight" | "infinity" => Self::FigureEight,
            "swiss-cross" | "swisscross" | "cross" | "swiss" => Self::SwissCross,
            "switzerland" | "ch" | "swiss-map" | "ch-outline" => Self::Switzerland,
            _ => return None,
        })
    }
}

fn regular_polygon(n: usize) -> Vec<(f64, f64)> {
    // Start the first vertex at the top (+y), so a non-rotated triangle points
    // north — matches geographic intuition.
    let mut out = Vec::with_capacity(n + 1);
    for i in 0..=n {
        let theta = (i as f64) * 2.0 * std::f64::consts::PI / (n as f64)
            + std::f64::consts::FRAC_PI_2;
        out.push((theta.cos(), theta.sin()));
    }
    out
}

fn star(points: usize, inner_ratio: f64) -> Vec<(f64, f64)> {
    let m = points * 2;
    let mut out = Vec::with_capacity(m + 1);
    for i in 0..=m {
        let r = if i % 2 == 0 { 1.0 } else { inner_ratio };
        let theta =
            (i as f64) * std::f64::consts::PI / (points as f64) + std::f64::consts::FRAC_PI_2;
        out.push((r * theta.cos(), r * theta.sin()));
    }
    out
}

fn heart(n: usize) -> Vec<(f64, f64)> {
    // Classic parametric heart. Normalised so max radius is 1.
    let mut raw: Vec<(f64, f64)> = (0..=n)
        .map(|i| {
            let t = (i as f64) * 2.0 * std::f64::consts::PI / (n as f64);
            let x = 16.0 * t.sin().powi(3);
            let y = 13.0 * t.cos()
                - 5.0 * (2.0 * t).cos()
                - 2.0 * (3.0 * t).cos()
                - (4.0 * t).cos();
            (x, y)
        })
        .collect();
    let r_max = raw
        .iter()
        .map(|p| (p.0 * p.0 + p.1 * p.1).sqrt())
        .fold(0.0_f64, f64::max)
        .max(1e-9);
    for p in &mut raw {
        p.0 /= r_max;
        p.1 /= r_max;
    }
    raw
}

fn figure_eight(n: usize) -> Vec<(f64, f64)> {
    // Lemniscate of Gerono: x = sin(t), y = sin(t) cos(t). Smooth ∞.
    (0..=n)
        .map(|i| {
            let t = (i as f64) * 2.0 * std::f64::consts::PI / (n as f64);
            (t.sin(), t.sin() * t.cos())
        })
        .collect()
}

/// Outline of Switzerland derived from the Natural Earth 1:50m country
/// border, simplified with Douglas-Peucker to ≈100 vertices (≈3.5 km
/// tolerance). Generated by `extract_ch_border.py`. Hand-tuning was
/// removed in favour of authoritative data — every (lat, lon) below
/// comes straight from the source dataset.
fn switzerland_outline() -> Vec<(f64, f64)> {
    // Each pair of consecutive points becomes one routing leg, so the ~3.5 km
    // simplification tolerance roughly caps how far the search can drift from
    // the real silhouette per leg.
    const POINTS: &[(f64, f64)] = &[
        (46.8644, 10.4538),
        (46.9366, 10.4585),
        (46.9955, 10.3790),
        (46.8471, 10.1113),
        (46.9274, 9.8751),
        (47.0155, 9.8580),
        (47.0639, 9.4770),
        (47.1080, 9.5124),
        (47.2100, 9.4874),
        (47.4521, 9.6503),
        (47.6501, 9.2732),
        (47.6561, 8.8817),
        (47.7200, 8.7976),
        (47.6946, 8.7171),
        (47.7574, 8.7131),
        (47.8012, 8.5582),
        (47.6655, 8.3913),
        (47.6563, 8.6073),
        (47.5894, 8.5607),
        (47.6220, 8.2330),
        (47.5606, 8.0423),
        (47.5953, 7.8197),
        (47.5443, 7.6834),
        (47.5647, 7.6097),
        (47.5950, 7.6370),
        (47.5423, 7.4827),
        (47.4382, 7.4063),
        (47.4168, 7.2381),
        (47.4436, 7.1683),
        (47.4883, 7.1808),
        (47.4891, 6.9733),
        (47.4522, 6.9910),
        (47.3542, 6.8666),
        (47.3681, 7.0040),
        (47.3295, 7.0366),
        (47.0213, 6.6654),
        (46.9442, 6.4426),
        (46.7608, 6.4292),
        (46.5835, 6.1184),
        (46.5516, 6.1457),
        (46.4194, 6.0542),
        (46.3593, 6.1364),
        (46.2464, 6.0897),
        (46.2120, 5.9585),
        (46.1305, 5.9588),
        (46.1386, 6.1079),
        (46.2401, 6.2812),
        (46.3155, 6.2141),
        (46.3945, 6.3016),
        (46.4559, 6.6137),
        (46.4142, 6.7871),
        (46.3455, 6.7504),
        (46.2695, 6.8277),
        (46.1348, 6.7743),
        (46.1123, 6.8692),
        (46.0496, 6.8509),
        (46.0486, 6.9151),
        (45.8902, 7.0669),
        (45.9078, 7.3618),
        (45.9841, 7.5411),
        (45.9145, 7.8312),
        (46.1270, 8.1106),
        (46.2718, 8.0873),
        (46.4522, 8.3992),
        (46.4124, 8.4458),
        (46.2354, 8.4381),
        (46.1228, 8.6018),
        (46.0897, 8.8089),
        (46.0664, 8.8344),
        (45.9831, 8.7679),
        (45.9471, 8.8710),
        (45.8264, 8.9000),
        (45.8207, 9.0024),
        (45.8990, 9.0631),
        (45.9644, 8.9805),
        (46.0393, 9.0021),
        (46.2312, 9.2248),
        (46.3314, 9.2752),
        (46.4851, 9.2632),
        (46.4983, 9.4346),
        (46.3753, 9.4444),
        (46.2986, 9.5365),
        (46.2918, 9.6743),
        (46.3509, 9.7201),
        (46.3712, 9.9184),
        (46.2205, 10.0427),
        (46.2311, 10.1179),
        (46.2624, 10.1589),
        (46.3381, 10.0924),
        (46.4029, 10.1408),
        (46.4463, 10.0263),
        (46.5330, 10.0328),
        (46.6044, 10.0878),
        (46.6268, 10.1921),
        (46.5511, 10.2954),
        (46.5377, 10.4440),
        (46.6236, 10.4591),
        (46.6724, 10.3692),
        (46.8644, 10.4538),
    ];
    let n_unique = POINTS.len() - 1;
    let lat_c: f64 = POINTS.iter().take(n_unique).map(|p| p.0).sum::<f64>()
        / n_unique as f64;
    let lon_c: f64 = POINTS.iter().take(n_unique).map(|p| p.1).sum::<f64>()
        / n_unique as f64;
    let cos_lat = lat_c.to_radians().cos();
    let mut raw: Vec<(f64, f64)> = POINTS
        .iter()
        .map(|(lat, lon)| ((lon - lon_c) * cos_lat, lat - lat_c))
        .collect();
    let r_max = raw
        .iter()
        .map(|p| (p.0 * p.0 + p.1 * p.1).sqrt())
        .fold(0.0_f64, f64::max)
        .max(1e-9);
    for p in &mut raw {
        p.0 /= r_max;
        p.1 /= r_max;
    }
    raw
}

fn swiss_cross() -> Vec<(f64, f64)> {
    // 12-vertex plus sign with arm thickness 1/3 of total span. Closed.
    let a = 1.0 / 3.0;
    vec![
        (-a, 1.0),
        (a, 1.0),
        (a, a),
        (1.0, a),
        (1.0, -a),
        (a, -a),
        (a, -1.0),
        (-a, -1.0),
        (-a, -a),
        (-1.0, -a),
        (-1.0, a),
        (-a, a),
        (-a, 1.0),
    ]
}

/// Largest distance from origin to any vertex (in unit space). Used by the
/// country-search sampler to inset the bbox so the shape doesn't escape it.
pub fn unit_max_radius(kind: ShapeKind) -> f64 {
    unit_vertices(kind)
        .iter()
        .map(|p| (p.0 * p.0 + p.1 * p.1).sqrt())
        .fold(0.0_f64, f64::max)
}

/// Perimeter of the unit-radius shape (sum of leg lengths). Used to invert
/// "I want a perimeter of P km" into the radius the shape needs.
pub fn unit_shape_perimeter(kind: ShapeKind) -> f64 {
    unit_perimeter(&unit_vertices(kind))
}

fn unit_vertices(kind: ShapeKind) -> Vec<(f64, f64)> {
    match kind {
        ShapeKind::Circle => regular_polygon(CIRCLE_SEGMENTS),
        ShapeKind::Triangle => regular_polygon(3),
        ShapeKind::Square => regular_polygon(4),
        ShapeKind::Pentagon => regular_polygon(5),
        ShapeKind::Hexagon => regular_polygon(6),
        ShapeKind::Star => star(5, 0.4),
        ShapeKind::Heart => heart(SMOOTH_CURVE_SEGMENTS),
        ShapeKind::FigureEight => figure_eight(SMOOTH_CURVE_SEGMENTS * 2),
        ShapeKind::SwissCross => swiss_cross(),
        ShapeKind::Switzerland => switzerland_outline(),
    }
}

fn unit_perimeter(verts: &[(f64, f64)]) -> f64 {
    let mut total = 0.0;
    for w in verts.windows(2) {
        let dx = w[1].0 - w[0].0;
        let dy = w[1].1 - w[0].1;
        total += (dx * dx + dy * dy).sqrt();
    }
    total
}

/// Place a closed shape on the sphere centred on `center`, sized so its
/// (unit-space) perimeter equals `perimeter_km`. `rotation_deg` rotates the
/// shape clockwise as seen from above (so 0° = pointing north, 90° = east).
///
/// Returns `n+1` vertices with `verts[0] == verts[n]` so consecutive-pair
/// iteration walks the closed loop without a special case at the wrap.
pub fn place_shape(
    center: LatLon,
    kind: ShapeKind,
    perimeter_km: f64,
    rotation_deg: f64,
) -> Vec<LatLon> {
    let unit = unit_vertices(kind);
    let unit_perim = unit_perimeter(&unit).max(1e-9);
    let radius_m = (perimeter_km * 1000.0) / unit_perim;
    let rot_rad = rotation_deg.to_radians();
    let mut out = Vec::with_capacity(unit.len());
    for (x, y) in unit {
        let r = (x * x + y * y).sqrt();
        if r < 1e-9 {
            out.push(center);
            continue;
        }
        let theta = y.atan2(x); // CCW from east, radians
        // Geographic bearing (CW from north) = π/2 − θ + rotation.
        let bearing = std::f64::consts::FRAC_PI_2 - theta + rot_rad;
        let dist = r * radius_m;
        out.push(destination(center, bearing, dist));
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::geodesy::haversine;

    #[test]
    fn circle_perimeter_matches_request() {
        let verts = place_shape(LatLon::new(46.8, 8.2), ShapeKind::Circle, 50.0, 0.0);
        let p_m: f64 = verts
            .windows(2)
            .map(|w| haversine(w[0], w[1]))
            .sum();
        assert!(
            (p_m - 50_000.0).abs() < 1_500.0,
            "circle perimeter {p_m:.0} m far from 50 000 m"
        );
        // Closed loop.
        let first = verts[0];
        let last = verts[verts.len() - 1];
        assert!(haversine(first, last) < 5.0);
    }

    #[test]
    fn triangle_has_three_legs_plus_close() {
        let verts = place_shape(LatLon::new(46.8, 8.2), ShapeKind::Triangle, 60.0, 0.0);
        assert_eq!(verts.len(), 4); // 3 vertices + close
    }

    #[test]
    fn rotation_changes_first_vertex_bearing() {
        let center = LatLon::new(46.8, 8.2);
        let v0 = place_shape(center, ShapeKind::Triangle, 60.0, 0.0)[0];
        let v90 = place_shape(center, ShapeKind::Triangle, 60.0, 90.0)[0];
        // 0° → first vertex due north (Δlat > 0, Δlon ≈ 0).
        assert!(v0.lat > center.lat);
        assert!((v0.lon - center.lon).abs() < 0.05);
        // 90° → first vertex due east (Δlat ≈ 0, Δlon > 0).
        assert!((v90.lat - center.lat).abs() < 0.05);
        assert!(v90.lon > center.lon);
    }

    #[test]
    fn parse_kind_accepts_aliases() {
        assert_eq!(ShapeKind::parse("circle"), Some(ShapeKind::Circle));
        assert_eq!(ShapeKind::parse("Heart"), Some(ShapeKind::Heart));
        assert_eq!(ShapeKind::parse("figure-8"), Some(ShapeKind::FigureEight));
        assert_eq!(ShapeKind::parse("swiss"), Some(ShapeKind::SwissCross));
        assert_eq!(ShapeKind::parse("switzerland"), Some(ShapeKind::Switzerland));
        assert_eq!(ShapeKind::parse("CH"), Some(ShapeKind::Switzerland));
        assert_eq!(ShapeKind::parse("blob"), None);
    }

    #[test]
    fn switzerland_outline_is_closed_and_normalised() {
        let v = switzerland_outline();
        assert!(v.len() >= 10, "outline should have plenty of points");
        // Closed: first == last.
        let first = v[0];
        let last = v[v.len() - 1];
        assert!((first.0 - last.0).abs() < 1e-9 && (first.1 - last.1).abs() < 1e-9);
        // Max radius normalised to ~1.
        let r_max = v
            .iter()
            .map(|p| (p.0 * p.0 + p.1 * p.1).sqrt())
            .fold(0.0_f64, f64::max);
        assert!((r_max - 1.0).abs() < 1e-6, "max radius {r_max}");
    }

    #[test]
    fn switzerland_perimeter_matches_request() {
        let verts = place_shape(LatLon::new(46.8, 8.2), ShapeKind::Switzerland, 80.0, 0.0);
        let p_m: f64 = verts
            .windows(2)
            .map(|w| crate::geodesy::haversine(w[0], w[1]))
            .sum();
        assert!(
            (p_m - 80_000.0).abs() < 2_000.0,
            "switzerland perimeter {p_m:.0} m far from 80 000 m"
        );
    }
}
